name: comfort_zone
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2  # Revert to your original working version
  google_sign_in: ^6.1.5
  google_sign_in_web: ^0.12.4  # Latest as of Feb 2025
  cloud_firestore: ^5.6.3
  fluttertoast: ^8.2.12
  shared_preferences: ^2.0.15
  http: 1.3.0
  logger: ^2.0.2
  cached_network_image: ^3.3.1
  jwt_decode: 0.3.1
  url_launcher: ^6.3.0
  


  # UI & State Management
  provider: ^6.1.2

  # Icons & Utilities
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.0
  khalti_flutter: ^3.0.0
  firebase_storage: ^12.4.3
  intl: ^0.18.1
  web_socket_channel: ^3.0.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.jpg
    - lib/assets/furniture_logo.jpg
    - lib/assets/chairs_image.jpg
    - lib/assets/tables_image.jpg
    - lib/assets/sofas_image.jpg
    - lib/assets/beds_image.jpg
    - lib/assets/custom_design_image.jpg
    - lib/assets/cupboard_image.jpg
    - lib/assets/google_logo.svg
    - lib/assets/chairs/office_chair.webp
    - lib/assets/chairs/gaming_chair.webp
    - lib/assets/chairs/wooden_chair.jpg
    - lib/assets/beds/king_bed.webp
    - lib/assets/beds/queen_bed.webp
    - lib/assets/beds/single_bed.webp
    - lib/assets/cupboard/glass_cupboard.jpg
    - lib/assets/cupboard/sliding_cupboard.webp
    - lib/assets/cupboard/wooden_cupboard.jpg
    - lib/assets/sofa/fabric_sofa.jpeg
    - lib/assets/sofa/leather_sofa.jpg
    - lib/assets/sofa/recliner_sofa.jpg
    - lib/assets/tables/coffee_table.jpg
    - lib/assets/tables/dining_table.jpg
    - lib/assets/tables/study_table.png
    - lib/assets/default_avatar.jpg