// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU01iocN3wND_LHoC0TrpfA5xPMpvUack',
    appId: '1:628073575006:web:17a7ae7f06e4e15109facf',
    messagingSenderId: '628073575006',
    projectId: 'comfort-zone-4d2bc',
    authDomain: 'comfort-zone-4d2bc.firebaseapp.com',
    storageBucket: 'comfort-zone-4d2bc.firebasestorage.app',
    measurementId: 'G-KSWG5TJ7KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjajmPLtFFMIBl8kNwLf5VVfsmxVvdBQ4',
    appId: '1:628073575006:android:1d5ad18f2001a9b809facf',
    messagingSenderId: '628073575006',
    projectId: 'comfort-zone-4d2bc',
    storageBucket: 'comfort-zone-4d2bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZRNyDtLqMTZJ0vlinNJ-FG2VaGsiRBQM',
    appId: '1:628073575006:ios:15a6f7bf9a90702009facf',
    messagingSenderId: '628073575006',
    projectId: 'comfort-zone-4d2bc',
    storageBucket: 'comfort-zone-4d2bc.firebasestorage.app',
    androidClientId: '628073575006-8vpljh7jne1h3en4l90dccfp5i87r4h7.apps.googleusercontent.com',
    iosClientId: '628073575006-ojcq7jmp3uni1l5qgk784cqesj9d29pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comfortZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZRNyDtLqMTZJ0vlinNJ-FG2VaGsiRBQM',
    appId: '1:628073575006:ios:15a6f7bf9a90702009facf',
    messagingSenderId: '628073575006',
    projectId: 'comfort-zone-4d2bc',
    storageBucket: 'comfort-zone-4d2bc.firebasestorage.app',
    androidClientId: '628073575006-8vpljh7jne1h3en4l90dccfp5i87r4h7.apps.googleusercontent.com',
    iosClientId: '628073575006-ojcq7jmp3uni1l5qgk784cqesj9d29pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.comfortZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU01iocN3wND_LHoC0TrpfA5xPMpvUack',
    appId: '1:628073575006:web:e15bef95af05c6da09facf',
    messagingSenderId: '628073575006',
    projectId: 'comfort-zone-4d2bc',
    authDomain: 'comfort-zone-4d2bc.firebaseapp.com',
    storageBucket: 'comfort-zone-4d2bc.firebasestorage.app',
    measurementId: 'G-K0MXNQZCVS',
  );

}